FROM nginx
MAINTAINER AZEMA Mickael mickael@azema.net
# Remove the default Nginx configuration file
RUN rm -v /etc/nginx/nginx.conf
# Copy a configuration file from the current directory
ADD nginx.conf /etc/nginx/

